version: '3.4'
services:
   ros-melodic:
      build: /home/pankhuri/Docker/compose-ros/ros-melodic/.
      ports:
         - "30000:30000/udp"

   ros-dashing:
      build: /home/pankhuri/Docker/compose-ros/ros-dashing/.
      ports:
         - "30001:30000/udp"
